//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnologiaTextil.FacturacionClientXP.ServiceEfact {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultFacturacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ResultFacturacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultListLog", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ResultListLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TamanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Tamano {
            get {
                return this.TamanoField;
            }
            set {
                if ((this.TamanoField.Equals(value) != true)) {
                    this.TamanoField = value;
                    this.RaisePropertyChanged("Tamano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEfact.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProcesaFacturaElectronica", ReplyAction="http://tempuri.org/IService/ProcesaFacturaElectronicaResponse")]
        TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultFacturacion ProcesaFacturaElectronica(string Tabla, string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/ProcesaFacturaElectronica", ReplyAction="http://tempuri.org/IService/ProcesaFacturaElectronicaResponse")]
        System.IAsyncResult BeginProcesaFacturaElectronica(string Tabla, string Usuario, System.AsyncCallback callback, object asyncState);
        
        TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultFacturacion EndProcesaFacturaElectronica(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerLog", ReplyAction="http://tempuri.org/IService/ObtenerLogResponse")]
        byte[] ObtenerLog(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/ObtenerLog", ReplyAction="http://tempuri.org/IService/ObtenerLogResponse")]
        System.IAsyncResult BeginObtenerLog(string Nombre, System.AsyncCallback callback, object asyncState);
        
        byte[] EndObtenerLog(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerListaLog", ReplyAction="http://tempuri.org/IService/ObtenerListaLogResponse")]
        TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultListLog[] ObtenerListaLog(string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/ObtenerListaLog", ReplyAction="http://tempuri.org/IService/ObtenerListaLogResponse")]
        System.IAsyncResult BeginObtenerListaLog(string Usuario, System.AsyncCallback callback, object asyncState);
        
        TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultListLog[] EndObtenerListaLog(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TecnologiaTextil.FacturacionClientXP.ServiceEfact.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcesaFacturaElectronicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ProcesaFacturaElectronicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultFacturacion Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultFacturacion)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerListaLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerListaLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultListLog[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultListLog[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TecnologiaTextil.FacturacionClientXP.ServiceEfact.IService>, TecnologiaTextil.FacturacionClientXP.ServiceEfact.IService {
        
        private BeginOperationDelegate onBeginProcesaFacturaElectronicaDelegate;
        
        private EndOperationDelegate onEndProcesaFacturaElectronicaDelegate;
        
        private System.Threading.SendOrPostCallback onProcesaFacturaElectronicaCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerLogDelegate;
        
        private EndOperationDelegate onEndObtenerLogDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerLogCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerListaLogDelegate;
        
        private EndOperationDelegate onEndObtenerListaLogDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerListaLogCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ProcesaFacturaElectronicaCompletedEventArgs> ProcesaFacturaElectronicaCompleted;
        
        public event System.EventHandler<ObtenerLogCompletedEventArgs> ObtenerLogCompleted;
        
        public event System.EventHandler<ObtenerListaLogCompletedEventArgs> ObtenerListaLogCompleted;
        
        public TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultFacturacion ProcesaFacturaElectronica(string Tabla, string Usuario) {
            return base.Channel.ProcesaFacturaElectronica(Tabla, Usuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginProcesaFacturaElectronica(string Tabla, string Usuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginProcesaFacturaElectronica(Tabla, Usuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultFacturacion EndProcesaFacturaElectronica(System.IAsyncResult result) {
            return base.Channel.EndProcesaFacturaElectronica(result);
        }
        
        private System.IAsyncResult OnBeginProcesaFacturaElectronica(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Tabla = ((string)(inValues[0]));
            string Usuario = ((string)(inValues[1]));
            return this.BeginProcesaFacturaElectronica(Tabla, Usuario, callback, asyncState);
        }
        
        private object[] OnEndProcesaFacturaElectronica(System.IAsyncResult result) {
            TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultFacturacion retVal = this.EndProcesaFacturaElectronica(result);
            return new object[] {
                    retVal};
        }
        
        private void OnProcesaFacturaElectronicaCompleted(object state) {
            if ((this.ProcesaFacturaElectronicaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ProcesaFacturaElectronicaCompleted(this, new ProcesaFacturaElectronicaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ProcesaFacturaElectronicaAsync(string Tabla, string Usuario) {
            this.ProcesaFacturaElectronicaAsync(Tabla, Usuario, null);
        }
        
        public void ProcesaFacturaElectronicaAsync(string Tabla, string Usuario, object userState) {
            if ((this.onBeginProcesaFacturaElectronicaDelegate == null)) {
                this.onBeginProcesaFacturaElectronicaDelegate = new BeginOperationDelegate(this.OnBeginProcesaFacturaElectronica);
            }
            if ((this.onEndProcesaFacturaElectronicaDelegate == null)) {
                this.onEndProcesaFacturaElectronicaDelegate = new EndOperationDelegate(this.OnEndProcesaFacturaElectronica);
            }
            if ((this.onProcesaFacturaElectronicaCompletedDelegate == null)) {
                this.onProcesaFacturaElectronicaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProcesaFacturaElectronicaCompleted);
            }
            base.InvokeAsync(this.onBeginProcesaFacturaElectronicaDelegate, new object[] {
                        Tabla,
                        Usuario}, this.onEndProcesaFacturaElectronicaDelegate, this.onProcesaFacturaElectronicaCompletedDelegate, userState);
        }
        
        public byte[] ObtenerLog(string Nombre) {
            return base.Channel.ObtenerLog(Nombre);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerLog(string Nombre, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerLog(Nombre, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public byte[] EndObtenerLog(System.IAsyncResult result) {
            return base.Channel.EndObtenerLog(result);
        }
        
        private System.IAsyncResult OnBeginObtenerLog(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Nombre = ((string)(inValues[0]));
            return this.BeginObtenerLog(Nombre, callback, asyncState);
        }
        
        private object[] OnEndObtenerLog(System.IAsyncResult result) {
            byte[] retVal = this.EndObtenerLog(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerLogCompleted(object state) {
            if ((this.ObtenerLogCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerLogCompleted(this, new ObtenerLogCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerLogAsync(string Nombre) {
            this.ObtenerLogAsync(Nombre, null);
        }
        
        public void ObtenerLogAsync(string Nombre, object userState) {
            if ((this.onBeginObtenerLogDelegate == null)) {
                this.onBeginObtenerLogDelegate = new BeginOperationDelegate(this.OnBeginObtenerLog);
            }
            if ((this.onEndObtenerLogDelegate == null)) {
                this.onEndObtenerLogDelegate = new EndOperationDelegate(this.OnEndObtenerLog);
            }
            if ((this.onObtenerLogCompletedDelegate == null)) {
                this.onObtenerLogCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerLogCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerLogDelegate, new object[] {
                        Nombre}, this.onEndObtenerLogDelegate, this.onObtenerLogCompletedDelegate, userState);
        }
        
        public TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultListLog[] ObtenerListaLog(string Usuario) {
            return base.Channel.ObtenerListaLog(Usuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerListaLog(string Usuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerListaLog(Usuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultListLog[] EndObtenerListaLog(System.IAsyncResult result) {
            return base.Channel.EndObtenerListaLog(result);
        }
        
        private System.IAsyncResult OnBeginObtenerListaLog(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Usuario = ((string)(inValues[0]));
            return this.BeginObtenerListaLog(Usuario, callback, asyncState);
        }
        
        private object[] OnEndObtenerListaLog(System.IAsyncResult result) {
            TecnologiaTextil.FacturacionClientXP.ServiceEfact.ResultListLog[] retVal = this.EndObtenerListaLog(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerListaLogCompleted(object state) {
            if ((this.ObtenerListaLogCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerListaLogCompleted(this, new ObtenerListaLogCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerListaLogAsync(string Usuario) {
            this.ObtenerListaLogAsync(Usuario, null);
        }
        
        public void ObtenerListaLogAsync(string Usuario, object userState) {
            if ((this.onBeginObtenerListaLogDelegate == null)) {
                this.onBeginObtenerListaLogDelegate = new BeginOperationDelegate(this.OnBeginObtenerListaLog);
            }
            if ((this.onEndObtenerListaLogDelegate == null)) {
                this.onEndObtenerListaLogDelegate = new EndOperationDelegate(this.OnEndObtenerListaLog);
            }
            if ((this.onObtenerListaLogCompletedDelegate == null)) {
                this.onObtenerListaLogCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerListaLogCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerListaLogDelegate, new object[] {
                        Usuario}, this.onEndObtenerListaLogDelegate, this.onObtenerListaLogCompletedDelegate, userState);
        }
    }
}
